### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The plugin could be easily published in the official repository (see comments in Google groups). In such case you won't need a custom installation procedure.

**Comment by ktf** [comment]
(Read the google thread) @LaisvydasLT to be clear, if you are happy with the plugin being hosted in the official jenkins repo I think this would be a fantastic opportunity and I would for sure support your work in that respect. Good job.

**Comment by oleg-nenashev** [comment]
The plugin definitely needs some improvements in the scope of the functionality and the code quality. BTW, in Jenkins project you can get external reviews and other contributions if you're ready to maintain the plugin during a significant timeframe.

**Comment by ktf** [comment]
Feedback is welcome, of course. @LaisvydasLT is currently in a stage here at CERN and will work on the plugin for a couple more months. In principle there is interest at CERN in anything Jenkins related so it might be we get other students in the future. If you are interested (or you know someone who would be interested) we are also participating in GSoC2015 under the CERN/SFT (the CERN Software Group) umbrella and a proposal to work on this would be well seen from our side (of course that does not guarantee it will be accepted by Google). In particular there is interest to support HTCondor.

**Pull request merged**
